# Generated by Django 5.0.6 on 2025-12-04 14:39

import django.db.models.deletion
import purchases.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRDII',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'CRDII',
                'verbose_name_plural': 'CRDIIs',
            },
        ),
        migrations.CreateModel(
            name='LogUso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=128)),
                ('detalhe', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('nao_concluido', 'Em Andamento'), ('concluido', 'Concluído'), ('parcial', 'Parcial'), ('arquivado', 'Arquivado'), ('cancelado', 'Cancelado')], default='nao_concluido', max_length=32)),
                ('data_em_andamento', models.DateTimeField(blank=True, null=True)),
                ('data_parcial', models.DateTimeField(blank=True, null=True)),
                ('data_concluido', models.DateTimeField(blank=True, null=True)),
                ('data_arquivado', models.DateTimeField(blank=True, null=True)),
                ('data_cancelado', models.DateTimeField(blank=True, null=True)),
                ('crdii', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='purchases.crdii')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('crdii', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_original', models.CharField(max_length=255)),
                ('nome_atual', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to=purchases.models.get_upload_path)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_criados', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='purchases.processo')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_anterior', models.CharField(blank=True, choices=[('nao_concluido', 'Em Andamento'), ('concluido', 'Concluído'), ('parcial', 'Parcial'), ('arquivado', 'Arquivado'), ('cancelado', 'Cancelado')], max_length=32, null=True)),
                ('status_novo', models.CharField(choices=[('nao_concluido', 'Em Andamento'), ('concluido', 'Concluído'), ('parcial', 'Parcial'), ('arquivado', 'Arquivado'), ('cancelado', 'Cancelado')], max_length=32)),
                ('data_mudanca', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='purchases.processo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-data_mudanca'],
            },
        ),
    ]
