# Generated by Django 5.2.7 on 2026-01-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arquivo",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("processo", "Processo"),
                    ("nota_fiscal", "Nota Fiscal"),
                    ("boletos", "Boletos"),
                ],
                default="processo",
                max_length=50,
                null=True,
            ),
        ),
    ]
