# Generated by Django 5.2.7 on 2026-01-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0003_alter_arquivo_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="tipo",
            field=models.CharField(
                choices=[("COMPRAS", "Compras"), ("DIVERSOS", "Diversos")],
                default="COMPRAS",
                max_length=20,
            ),
        ),
    ]
