# Generated by Django 5.0.6 on 2025-12-04 14:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('administrador', 'Administrador'), ('gestor', 'Gestor'), ('diretoria', 'Diretoria'), ('compras', 'Compras'), ('obra', 'Obras'), ('financeiro', 'Financeiro'), ('dev', 'Desenvolvedor')], default='dev', max_length=15, verbose_name='Papel')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenants', models.ManyToManyField(blank=True, related_name='users', to='tenants.empresa', verbose_name='Empresas')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('page_dashboard', 'Pode visualizar a página Dashboard'), ('page_compras', 'Pode visualizar a página de Processos'), ('page_admin', 'Pode visualizar a página de Administração (Usuários)'), ('can_create_processo', 'Pode criar novos processos'), ('can_edit_processo', 'Pode editar processos existentes'), ('can_delete_processo', 'Pode excluir processos'), ('can_change_status', 'Pode alterar o status de um processo'), ('can_upload_file', 'Pode fazer upload de arquivos'), ('can_delete_file', 'Pode excluir arquivos'), ('can_edit_user', 'Pode editar outros usuários')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_dashboard', models.BooleanField(default=True)),
                ('page_compras', models.BooleanField(default=True)),
                ('page_admin', models.BooleanField(default=False)),
                ('can_create_processo', models.BooleanField(default=False)),
                ('can_edit_processo', models.BooleanField(default=False)),
                ('can_delete_processo', models.BooleanField(default=False)),
                ('can_change_status', models.BooleanField(default=False)),
                ('can_upload_file', models.BooleanField(default=False)),
                ('can_delete_file', models.BooleanField(default=False)),
                ('can_edit_user', models.BooleanField(default=False)),
                ('view_status_history', models.BooleanField(default=False)),
                ('status_limits', models.JSONField(blank=True, default=dict, null=True)),
                ('allowed_crdii', models.JSONField(blank=True, default=list, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='tenants.empresa', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão de Usuário',
                'verbose_name_plural': 'Permissões de Usuários',
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
