# Generated by Django 5.2.7 on 2025-12-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="can_create_tenant",
            field=models.BooleanField(
                default=False, verbose_name="Pode Criar Empresas"
            ),
        ),
    ]
