# Generated by Django 5.2.7 on 2025-12-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_can_create_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermission",
            name="can_delete_user",
            field=models.BooleanField(default=False),
        ),
    ]
