# Generated by Django 5.2.7 on 2025-12-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userpermission_can_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpermission",
            name="page_admin",
        ),
        migrations.AddField(
            model_name="userpermission",
            name="gerenciar",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="relatorios",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
