# Generated by Django 5.2.7 on 2026-01-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_userpermission_page_admin_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("page_dashboard", "Pode visualizar a página Dashboard"),
                    ("page_compras", "Pode visualizar a página de Processos"),
                    (
                        "page_admin",
                        "Pode visualizar a página de Administração (Usuários)",
                    ),
                    ("can_create_processo", "Pode criar novos processos"),
                    ("can_edit_processo", "Pode editar processos existentes"),
                    ("can_delete_processo", "Pode excluir processos"),
                    ("can_change_status", "Pode alterar o status de um processo"),
                    ("can_upload_file", "Pode fazer upload de arquivos"),
                    ("can_download_file", "Pode fazer download de arquivos"),
                    ("can_delete_file", "Pode excluir arquivos"),
                    ("can_edit_user", "Pode editar outros usuários"),
                ]
            },
        ),
        migrations.AddField(
            model_name="userpermission",
            name="can_download_file",
            field=models.BooleanField(default=False),
        ),
    ]
