# Generated by Django 5.2.7 on 2026-01-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermission",
            name="can_download_boletos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="can_download_nota_fiscal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="can_download_processo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="can_upload_boletos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="can_upload_nota_fiscal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="can_upload_processo",
            field=models.BooleanField(default=False),
        ),
    ]
